In [1]:
from numpy import *

In [2]:
U, Sigma, VT = linalg.svd([[1, 1], [7, 7]])

In [3]:
U

array([[-0.14142136, -0.98994949],
       [-0.98994949,  0.14142136]])

In [4]:
Sigma

array([1.00000000e+01, 2.82797782e-16])

In [5]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [6]:
diag(Sigma)

array([[1.00000000e+01, 0.00000000e+00],
       [0.00000000e+00, 2.82797782e-16]])

In [7]:
U@diag(Sigma)@VT

array([[1., 1.],
       [7., 7.]])